### ISSUE TITLE
你好，想请教大牛个 OMR 问题呢

### ISSUE THREAD

**Issue by superlangs** [lizhichao/one-app#1]
你好 ，想请教一个问题，我也是很喜欢laravel的ORM，但是对于laravel的性能实在是有点遗憾，一直在寻找提升laravel的方法，找了一些的提升swool提升laravel的扩张，感觉坑太多，于是自己找了个 mixphp 的swoole的框架，自己集成laravel 的 ORM 到它的里面，但是发现每次首次访问接口的时候，会报 " PDO::prepare(): send of 62 bytes failed with errno=32 Broken pipe " 的错误，网上找了很多方法，都没有解决，碰巧看到大牛也是自己集成了 laravel的ORM，想请教下

**Comment by lizhichao** [comment]
不了解你是怎么集成的，不过传统的orm不全面的改造在swoole协程环境会有很多问题。你可以自己并发压测一下。你可以试试one，简单 灵活。你用过laravel看完readme应该就没有什么大问题了

**Comment by superlangs** [comment]
好的，谢谢
