### ISSUE TITLE
刚安装了个，默认 http server 配置，ab 测试的时候，发现错误,	ERROR	check_bind (ERROR 10002): Socket#126 has already been bound to another coroutine#37, reading or writing of the same socket in multiple coroutines at the same time is not allowed.

### ISSUE THREAD

**Issue by superlangs** [lizhichao/one-app#2]

**Comment by superlangs** [comment]
大牛，开启携程模式，有问题吧

**Comment by lizhichao** [comment]
有测试的代码吗？

**Comment by superlangs** [comment]
![image](https://user-images.githubusercontent.com/49265759/56022829-25340600-5d3f-11e9-8ace-e4681e1cec24.png)
这是我我写的一个方法

**Comment by lizhichao** [comment]
数据库是不是长连接配置？ 731475644 加qq群

**Comment by superlangs** [comment]
好，我加下群，
这个是我的数据库配置;
![image](https://user-images.githubusercontent.com/49265759/56023142-d470dd00-5d3f-11e9-9959-82b59b96f9a2.png)

**Comment by superlangs** [comment]
PDO::ATTR_PERSISTENT 改为false ,还是一样的，报错

**Comment by lizhichao** [comment]
升级swoole版本
